# Source: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle


image: 10.1.1.3/svwsnrw/docker-runner:21

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache: &global_cache
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
        - ./**/build
        - .gradle_user
        - .gradle

stages:
    - build
    - test
    - cleanup
    - analyze
    - build_snapshot_installer
    - build_installer
    - sign
    - publish

build:
    stage: build
    interruptible: true
    cache:
        <<: *global_cache
        policy: pull
    script:
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew --build-cache build -Penvironment=build
    artifacts:
        when: always
        reports:
            junit: ./**/build/test-results/test/**/TEST-*.xml
        paths:
            - "./build/**"
            - "./**/build/**"
        expire_in: "1 days"
    when: always

test:integration-tests:
    image: ${REGISTRY_HOST}/svws-ci/test-runner:jdk21-node22-playwright1.56
    dependencies:
        - build
    stage: test
    interruptible: true
    variables:
        USE_SYSTEM_NODE: "1" # Node aus dem Test-Runner Image wird verwendet und nicht erneut heruntergeladen
    before_script:
        - chmod +x ./.gitlab/.script/*.sh
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh

        - ./.gitlab/.script/docker_login.sh ${REGISTRY_HOST} ${REGISTRY_USER} ${REGISTRY_PASSWORD}
    script:
          ./gradlew --build-cache tests:integrationTest --stacktrace
    cache:
        <<: *global_cache
        policy: pull
    artifacts:
        when: always
        expire_in: "7 days"
        paths:
            - ./tests/tests-e2e-*/build/test-results
        reports:
            junit: ./tests/**/build/test-results/**/*.xml

cleanup:integration-tests:
    stage: cleanup
    before_script:
        - chmod +x ./.gitlab/.script/*.sh
    script:
        - ./.gitlab/.script/cleanup_integration_test_container.sh $CI_COMMIT_SHORT_SHA
    when: always
    allow_failure: true

analyze:sonarqube:
    stage: analyze
    interruptible: true
    only:
        - dev
    script:
        - ./gradlew sonar -Dsonar.projectKey=svws-server -Dsonar.host.url=$SONAR_URL -Dsonar.token=$SONAR_TOKEN --full-stacktrace
    when: manual

build_snapshot_windows:
    stage: build_snapshot_installer
    needs:
        - build
        - test:integration-tests
    image: 10.1.1.3/svwsnrw/docker-runner-wine:21
    script:
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew :deployment:windows-installer:doZip
        - mkdir artifacts_windows
        - cp ./deployment/windows-installer/build/output/win64-installer* ./artifacts_windows/
    artifacts:
        paths:
            - artifacts_windows/
    when: manual

build_linux:
    stage: build_installer
    rules:
       - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    needs:
        - job: build
    script:
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew :deployment:linux-installer:buildLinuxInstaller
        - mkdir artifacts_linux
        - cp -r ./deployment/linux-installer/build/distributions/ ./artifacts_linux
    artifacts:
        paths:
            - artifacts_linux/

build_windows:
    stage: build_installer
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    needs:
        - job: build
    image: 10.1.1.3/svwsnrw/docker-runner-wine:21
    script:
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew :deployment:windows-installer:doZip
        - mkdir artifacts_windows
        - cp ./deployment/windows-installer/build/output/win64-installer* ./artifacts_windows/
    artifacts:
        paths:
            - artifacts_windows/

sign_artifacts:
    stage: sign
    image: 10.1.1.3/svwsnrw/docker-runner:17
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    needs:
        - job: build
        - job: build_windows
        - job: build_linux
    before_script:
        - chmod u+x config/signing/*.sh
    script:
        - ./gradlew signJars signWindowsInstaller
    artifacts:
        paths:
            - artifacts_windows/
            - artifacts_linux/
        exclude:
            - "./build/signing/**/*"
            - "./build/signing"

publish_all:
    stage: publish
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    variables:
        SECURE_FILES_DOWNLOAD_PATH: '/'
    needs:
        - job: build
        - job: sign_artifacts
    script:
        - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
        - cat gradle_secure.properties >> gradle.properties
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew publishReleaseAll

publish_maven:
    stage: publish
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    variables:
        SECURE_FILES_DOWNLOAD_PATH: '/'
    needs:
        - job: build
        - job: sign_artifacts
    script:
        - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
        - cat gradle_secure.properties >> gradle.properties
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository

publish_dockerhub:
    stage: publish
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    variables:
        SECURE_FILES_DOWNLOAD_PATH: '/'
    needs:
        - job: build
        - job: sign_artifacts
    script:
        - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
        - cat gradle_secure.properties >> gradle.properties
        - cat dockerlogin.txt | docker login --username svwsnrw --password-stdin
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew :deployment:docker:dockerPushAllDockerhub

publish_github:
    stage: publish
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    variables:
        SECURE_FILES_DOWNLOAD_PATH: '/'
    needs:
        - job: build
        - job: sign_artifacts
    script:
        - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
        - cat gradle_secure.properties >> gradle.properties
        - chmod +x ./deployment/setupVersion.sh
        - ./deployment/setupVersion.sh
        - ./gradlew :deployment:githubRelease
